Adds support for RHEL9
stackhpc/ansible-role-sriov pull request #10
Opened 2023-04-05 14:10 UTC by jovial

2023-04-05 15:27 UTC, markgoddard requested changes

2023-04-05 15:27 UTC, markgoddard commented on tasks/config.yml
> +      - ^iommu=pt
```suggestion
      - ^iommu=
```

2023-04-05 17:57 UTC, oneswig approved these changes, later dismissed
Looks good thanks.  One or two minor points if you need to respin the PR.

2023-04-05 17:57 UTC, oneswig commented on README.md
> +        on_boot_configuration_enabled: false
We need this setting for VF-LAG environments and if you're respinning this it may be helpful to document the purpose of this flag.

2023-04-05 17:57 UTC, oneswig commented on tasks/config.yml
> +- name: Add iommu to kernel command line (Intel)
Is there no AMD equivalent required?

2023-04-20 10:00 UTC, jovial commented on README.md
> +        on_boot_configuration_enabled: false
Good call, I'll add.

2023-04-20 10:00 UTC, jovial commented on tasks/config.yml
> +- name: Add iommu to kernel command line (Intel)
For AMD CPUs (AMD-Vi), it is on if kernel detects IOMMU hardware support from BIOS.
Source: https://wiki.archlinux.org/title/PCI_passthrough_via_OVMF

2023-04-20 10:00 UTC, jovial commented on README.md
> +        # Don't add a udev rule to set numvfs
```suggestion
        # Don't add a udev rule to set numvfs. This can be useful if you use an alternative method
        # to set the number of virtual functions e.g some custom scripts to enable VFLAG, but want
        # to use the role to set firmware parameters.
```

2023-04-20 10:39 UTC, markgoddard approved these changes

2023-04-20 11:21 UTC, merged